export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_CLOSE = 'WS_CONNECTION_CLOSE';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';
export const WS_USER_NAME_UPDATE = 'WS_USER_NAME_UPDATE';

export const WS_WITH_TOKEN_CONNECTION_START = 'WS_WITH_TOKEN_CONNECTION_START';
export const WS_WITH_TOKEN_CONNECTION_CLOSE = 'WS_WITH_TOKEN_CONNECTION_CLOSE';
export const WS_WITH_TOKEN_CONNECTION_SUCCESS = 'WS_WITH_TOKEN_CONNECTION_SUCCESS';
export const WS_WITH_TOKEN_CONNECTION_ERROR = 'WS_WITH_TOKEN_CONNECTION_ERROR';
export const WS_WITH_TOKEN_CONNECTION_CLOSED = 'WS_WITH_TOKEN_CONNECTION_CLOSED';
export const WS_WITH_TOKEN_GET_MESSAGE = 'WS_WITH_TOKEN_GET_MESSAGE';
export const WS_WITH_TOKEN_SEND_MESSAGE = 'WS_WITH_TOKEN_SEND_MESSAGE';
export const WS_WITH_TOKEN_USER_NAME_UPDATE = 'WS_WITH_TOKEN_USER_NAME_UPDATE';

export const WS_START_HEARTBEAT = 'WS_START_HEARTBEAT';
export const WS_WITH_TOKEN_START_HEARTBEAT = 'WS_WITH_TOKEN_START_HEARTBEAT';
export const WS_STOP_HEARTBEAT = 'WS_STOP_HEARTBEAT';
export const WS_WITH_TOKEN_STOP_HEARTBEAT = 'WS_WITH_TOKEN_STOP_HEARTBEAT';
