export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_REQUEST_SUCCESS =
    'PROFILE_REQUEST_SUCCESS';
export const PROFILE_REQUEST_FAIL =
    'PROFILE_REQUEST_FAIL';
export const PROFILE_REQUEST_CLEAR_STATE =
    'PROFILE_REQUEST_CLEAR_STATE';
